Fix some invalid javascript
test plan:
These should never cause:
SyntaxError: 'arguments' is not allowed in class field initializer

Change-Id: I91e278ee8f5e01461e4d1f760822797f6070604f
Reviewed-on: https://gerrit.instructure.com/162071
Reviewed-by: Steven Burnett <sburnett@instructure.com>
Tested-by: Jenkins
Product-Review: Ryan Shaw <ryan@instructure.com>
QA-Review: Ryan Shaw <ryan@instructure.com>