ignore extra attributes from cas response
fixes: CNVS-13703

Adds a configuration to the rubycas-client gem to parse extra attributes
as a raw version since it defaults to parsing as yaml.

Test Plan:

- In a CAS response add some additional data that cannot be parsed as
  yaml.
- Without this fix it should throw an error that the extra attributes
  cannot be parsed as yaml.

Error: Failed to validate CAS ticket: #<ArgumentError: Error parsing extra
       attribute with value...

Change-Id: I464c296fcf129bc882420f5f4f3913ac37585b02
Reviewed-on: https://gerrit.instructure.com/37191
Tested-by: Jenkins <jenkins@instructure.com>
Reviewed-by: Brian Palmer <brianp@instructure.com>
QA-Review: August Thornton <august@instructure.com>
Product-Review: Nick Cloward <ncloward@instructure.com>