Disabling VeriCite can break an existing assignment for students
If VeriCite is disabled, an existing assignment that was previously used with VeriCite will not load the student Assignment Details Page. The following error is shown:
undefined method `empty?' for nil:NilClass /usr/src/app/app/views/assignments/_vericite.html.erb:8:in `_app_views_assignments__vericite_html_erb___4191980350643658434_60360200'

Test Plan:
-Create an assignment with VeriCite enabled
-As a student submit to the assignment
-Wait for a VeriCite score
-As an admin disable VeriCite
-As a student navigate to the assignment page (/courses/11/assignments/73)
-Make sure the student does not see a page load error