fix leaked React roots in AssignmentGroup tests
afterEach used $el.remove() (jQuery) instead of
Backbone's remove(), so child AssignmentListItemView
instances never called cleanupDateDueColumn/
cleanupDateAvailableColumn, causing:
  ReferenceError: window is not defined

CollectionView does not perform remove() to item views
on parent removal, so child views must be explicitly
removed before removing the parent.

flag=none

test plan:
  - Jenkins passes
  - JS stage does not throw error

Change-Id: Ic9dfc73a33e5f6a9e577676295733ab51d41dd1a
Reviewed-on: https://gerrit.instructure.com/c/canvas-lms/+/407165
Reviewed-by: Michael Hulse <michael.hulse@instructure.com>
Tested-by: Service Cloud Jenkins <svc.cloudjenkins@instructure.com>
QA-Review: James Butters <jbutters@instructure.com>
Product-Review: James Butters <jbutters@instructure.com>