Verify if end_at isn't nil and avoid 500 error
We were getting an error: "undefined method `<' for nil:NilClass"
when the course end_at is nil but restrict_enrollments_to_course_dates
was set to true. This solves it. To test further remove the change on
enrollment_type.rb and try running the new test, error will happen.

closes VICE-3405
flag=react_inbox

test plan:
  - Specs pass.

qa risk: low

Change-Id: Ic26f0872481ce8acd18365505b42c7e46a06a560
Reviewed-on: https://gerrit.instructure.com/c/canvas-lms/+/313700
Reviewed-by: Jason Gillett <jason.gillett@instructure.com>
Product-Review: Jason Gillett <jason.gillett@instructure.com>
Tested-by: Service Cloud Jenkins <svc.cloudjenkins@instructure.com>
QA-Review: Chawn Neal <chawn.neal@instructure.com>